# Generated by Django 3.1.7 on 2021-03-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=60)),
                ('receiver', models.CharField(max_length=60)),
                ('score_technical', models.DecimalField(decimal_places=0, max_digits=1)),
                ('score_social', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('slack_user_id', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('avg_score_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_score_social', to='api.score')),
                ('avg_score_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_score_tech', to='api.score')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
                'unique_together': {('slack_user_id',)},
            },
        ),
        migrations.AddField(
            model_name='score',
            name='scoresUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresUser', to='api.user'),
        ),
    ]
