# Generated by Django 3.1.7 on 2021-03-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avg_score_social',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avg_score_tech',
        ),
    ]
