# Generated by Django 3.1.7 on 2021-03-23 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='data_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='score',
            name='data_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
