# Generated by Django 3.1.7 on 2021-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210323_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
